
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	elm_win_indicator_mode_set(get_window(parent), ELM_WIN_INDICATOR_SHOW);
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	uib_views_get_instance()->set_targeted_view(vc->view_name);

	//bind event handler


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);

	return (uib_view_context*)vc;
}
void uib_view1_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->image1) {
			vc->image1 = elm_image_add(vc->grid1);
		}
		if(vc->image1) {
			char *resource_path = NULL;
			uib_util_rm_get_resource_path(-1, "down.png", &resource_path);
			elm_image_file_set(vc->image1, resource_path, NULL);
			if(resource_path) {
				free(resource_path);
			}
			elm_image_smooth_set(vc->image1, EINA_TRUE);
			elm_image_no_scale_set(vc->image1, EINA_FALSE);
			elm_image_resizable_set(vc->image1, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->image1, EINA_FALSE);
			elm_image_fill_outside_set(vc->image1, EINA_FALSE);
			elm_image_editable_set(vc->image1, EINA_FALSE);
			evas_object_size_hint_align_set(vc->image1, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->image1, 1.0, 1.0);
			evas_object_show(vc->image1);
		}
		if (!vc->label1) {
			vc->label1 = elm_label_add(vc->grid1);
		}
		if(vc->label1) {
			evas_object_size_hint_align_set(vc->label1, 1, 0.5);			evas_object_size_hint_weight_set(vc->label1, 1.0, 1.0);			elm_label_line_wrap_set(vc->label1, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label1,0);
			elm_label_ellipsis_set(vc->label1, EINA_FALSE);
			evas_object_show(vc->label1);
		}
		if (!vc->On) {
			vc->On = elm_button_add(vc->grid1);
		}
		if (vc->On) {
			evas_object_size_hint_align_set(vc->On, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->On, 1.0, 1.0);			elm_object_text_set(vc->On,_UIB_LOCALE("On"));
			elm_object_style_set(vc->On,"bottom");
			evas_object_show(vc->On);
		}
		elm_grid_pack(vc->grid1, vc->image1, 200, 136, 642, 423);		elm_grid_pack(vc->grid1, vc->label1, 187, 564, 667, 175);		elm_grid_pack(vc->grid1, vc->On, 322, 702, 364, 364);		evas_object_show(vc->grid1);
	}
}

